flask_app/forum/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash, Flask
from flask_login import current_user, login_required, login_user, logout_user
from flask_mongoengine import MongoEngine
from flask_mail import Mail, Message
from .. import bcrypt
from flask_app.forms import SearchForm, QuestionForm, AnswerForm,LikesForm
from ..models import User, Question, Answer
from flask_app import db
from datetime import datetime
from flask_app.utils import current_time

forum = Blueprint("forum", __name__)

app = Flask(__name__)
mail = Mail(app)
# I only got it to work with outlook 
MAIL_USERNAME = "cmsc388j@outlook.com" #'yourId@gmail.com' use an outlook account
MAIL_PASSWORD = "cmscfinal388j" # password don't merge if using your own

app.config['MAIL_SERVER']='smtp-mail.outlook.com'
app.config['MAIL_PORT'] = 587
# Enter your own email credentials here for testing and remove
# before pushing on github
app.config['MAIL_USERNAME'] = MAIL_USERNAME
app.config['MAIL_PASSWORD'] = MAIL_PASSWORD
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USE_SSL'] = False
mail = Mail(app)


@forum.route("/", methods=["GET", "POST"])
@forum.route("/forum", methods=["GET", "POST"])
def index():
    search_form = SearchForm()
    if search_form.validate_on_submit():
        return redirect(url_for("forum.search_results", query=search_form.search_query.data))
    return render_template("index.html", search_form=search_form)

@forum.route("/see_all_questions",methods=["GET", "POST"])
def see_all_questions():
    all_posts = Question.objects.all()
    return render_template("see_all_questions.html", questions=all_posts)

#View function for searching in questions
@forum.route("/search_results/<query>", methods=["GET", "POST"])
def search_results(query):
    search_results = Question.objects(title__icontains=query)
    return render_template("search_results.html", search_results=search_results, query=query)

@forum.route("/question/<question_id>", methods=["GET", "POST"])
def see_question(question_id):
    question = Question.objects(id=question_id).first()
    answer_form = AnswerForm()
    likes_form = LikesForm()
    if answer_form.validate_on_submit():
        answer = Answer(
            commenter=current_user,
            question=question,
            description=answer_form.answer.data,
            date=current_time(),
        )
        answer.save()
        question.answers.append(answer)
        question.save()

        # Send email to person who asked question that a user answered
        try:
            msg = Message('Hello', sender=MAIL_USERNAME, recipients=[question.commenter.email, MAIL_USERNAME])
            msg.body = answer.commenter.username + "responded to your question!"
            mail.send(msg)
        except:
            failed_send = "Failed to send email please check your email credentials"
            flash(failed_send, "danger")
            return redirect(url_for("forum.see_question", question_id=question_id))

        return redirect(url_for("forum.see_question", question_id=question_id))

    if likes_form.validate_on_submit():
        question.likes += 1
        question.save()
        # Find the user who made the post and increment their total likes
        user = User.objects(username=question.commenter.username).first()
        user.total_likes += 1
        user.likes_over_time.append([current_time(),user.total_likes])
        user.save()
        return redirect(url_for("forum.see_question", question_id=question_id))

    return render_template("see_question.html",
                           question=question,
                           answer_form=answer_form,
                           answers=question.answers,
                           likes_form=likes_form)

# TODO make sure the route is correct
@forum.route("/posts", methods=["GET", "POST"])
@login_required
def make_post():
    # TODO make sure the below works
    form = QuestionForm()
    dublicate_flag = False
    try:
        if form.validate_on_submit() and current_user.is_authenticated:
            post = Question(
                commenter=current_user._get_current_object(),
                title=form.title.data,
                description=form.description.data,
                date=current_time(),
                likes=0,
            )
            post.save()
            print("test")
            return redirect(url_for("forum.see_question", question_id=post.id))
    except:
        dublicate_flag = True
        title = form.title.data
        ref = Question.objects(title = title).first()
        return render_template("make_post.html", form=form, id_reference=ref.id, dublicate_flag=dublicate_flag)

    return render_template("make_post.html", form=form)

  #  # TODO Figure out what questions should be... I think maybe we don't need this line below
  #  questions = Question.objects(commenter=current_user._get_current_object())

   # # TODO render appropriate template with corresponding data for it
   # return render_template("404.html", form=form)


# TODO make sure the route is correct
@forum.route("/posts/<post_title>", methods=["GET", "POST"])
@login_required
def make_reply(post_title):
    try:
        result = Question.objects(title=post_title)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("forum.login"))
    # TODO make sure the below works
    form = AnswerForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        post = Answer(
            commenter=current_user._get_current_object(),
            question=Question.objects(title=post_title),
            description=form.description.data,
            date=current_time()
        )
        post.save()
        return redirect(request.path)

    # TODO Figure out what answers should be...
    answers = Answer.objects(question=Question.objects(title=post_title))

    # TODO render appropriate template with corresponding data for it
    return render_template("404.html", form=form)
@forum.route("/about")
def about():
    return render_template("about.html")

if __name__ == '__main__':
   app.run(debug = True)

flask_app/loginregistration/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import LoginForm, RegisterForm
from ..models import User

loginreg = Blueprint("loginreg", __name__)

@loginreg.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("forum.index"))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.objects(email=form.email.data).first()

        if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for("profile.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("loginreg.login"))
    return render_template("login.html", form=form)

@loginreg.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("forum.index"))

    form = RegisterForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed, about_me=form.about_me.data)
        user.save()

        return redirect(url_for("loginreg.login"))

    return render_template("register.html", form=form)

@loginreg.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("forum.index"))

flask_app/profile/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request,send_file
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import UpdateProfileForm
from ..models import User, Question, Answer

import io
import base64
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
import seaborn as sns
import matplotlib

profile = Blueprint("profile", __name__)

@profile.route("/account", methods=["GET", "POST"])
@login_required
def account():
    profile_form = UpdateProfileForm()
    user = User.objects(username=current_user.username).first()
    questions = Question.objects(commenter=user)
    answers = Answer.objects(commenter=user)
    likes_present = False if user.total_likes == 0 else True
    #Get likes over time
    likes_over_time = user.likes_over_time
    if len(likes_over_time) > 0:
        x = likes_over_time[0][:]
        y = likes_over_time[1][:]
    else:
        x = None
        y = None



    if profile_form.validate_on_submit():
        current_user.modify(username=profile_form.username.data, about_me=profile_form.about_me.data)
        current_user.save()
        return redirect(url_for("profile.account"))


    return render_template("account.html",
                           profile_form=profile_form,
                           questions=questions,
                           answers=answers,
                           likes_present=likes_present,
                           x = x,
                           y = y)

@profile.route("/vizualise_likes", methods=["GET", "POST"])
@login_required
def vizualise_likes():
    matplotlib.use('SVG')
    # Set sns style
    sns.set_style("darkgrid")
    fig,ax = plt.subplots(figsize=(10,5))
    user = User.objects(username=current_user.username).first()
    list_of_likes = user.likes_over_time
    x = [date[0] for date in list_of_likes]
    y = [date[1] for date in list_of_likes]
    print(x)
    sns.lineplot(x=x, y=y,ci=None)
    ax.set_xticklabels(x, rotation=0)
    canvas = FigureCanvas(fig)
    img = io.BytesIO()
    fig.savefig(img, format='png')
    img.seek(0)
    return send_file(img, mimetype='image/png')

flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}
    <div class="container">
    <h2>About the project</h2>
    </div>
    <div class="container">
            <p> This is the final project for CMSC388j, in which we made a forum for asking questions regarding different subjects</p>
            <br>
            <h3> The project was made by:</h3>
            <p> Edward Du, Hamzah Siddique and Mads Andersen </p>
    </div>
{% endblock %}

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>{{ current_user.username }}</h2>
    </div>
</div>
{% if current_user.about_me %}
<p>{{ current_user.about_me }}</p>
{% endif %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h2>Update Profile</h2>
                <form action="" method="post">
                    {{ profile_form.csrf_token }}
                    <div class="form-group">
                        {{ profile_form.username.label(class="form-control-label") }}
                        {{ profile_form.username(class="form-control form-control-lg") }}

                        {% if profile_form.username.errors %}
                        <div class="alert alert-warning" role="alert">
                            {% for error in profile_form.username.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ profile_form.about_me.label(class="form-control-label") }}
                        {{ profile_form.about_me(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{ profile_form.submit(class="form-control form-control-lg") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="questions-tab" data-toggle="tab" href="#questions" role="tab"
                    aria-controls="questions" aria-selected="true">Questions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="answers-tab" data-toggle="tab" href="#answers" role="tab"
                    aria-controls="answers" aria-selected="false">Answers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="stats-tab" data-toggle="tab" href="#stats" role="tab" aria-controls="stats"
                    aria-selected="false">Likes over time</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="questions" role="tabpanel" aria-labelledby="questions-tab">
                <h1> Questions <small class="float-right">{{ questions.count() }} questions asked</small></h1>
                <ul class="media-list">
                    {% for question in questions %}
                    <li class="media review-item">
                        <div class="media-body">
                            <span class="float-right">
                                <small>{{ question.date }}</small>
                            </span>
                            <strong>
                                <a href="{{ url_for('forum.see_question', question_id=question.id) }}">{{ question.title }}</a>
                            </strong>
                            <p>
                                {{ question.description }}
                            </p>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="tab-pane fade" id="answers" role="tabpanel" aria-labelledby="answers-tab">
                <h1> Answers <small class="float-right">{{ answers.count() }} answers given</small></h1>
                <ul class="media-list">
                    {% for answer in answers %}
                    <li class="media review-item">
                        <div class="media-body">
                            <span class="float-right">
                                <small>{{ answer.date }}</small>
                            </span>
                            <strong>
                                For <a href="{{ url_for('forum.see_question', question_id=answer.question.id) }}">{{ answer.question.title }}</a>
                            </strong>
                            <p>
                                {{ answer.description }}
                            </p>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="tab-pane fade" id="stats" role="tabpanel" aria-labelledby="stats-tab">
                {% if likes_present %}
                <h1> Likes over time </h1>
                <div id="chart_div">
                    <img src="{{ url_for('profile.vizualise_likes') }}" alt="Seaborn plot">
                </div>
                {% else %}
                <h3> No likes to show yet </h3>
                {% endif %}
            </div>
        </div>
        {% endblock %}
    </div>
</div>

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Forum</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ url_for('forum.index') }}">Forum Website</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('profile.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('loginreg.logout') }}">
                    Logout
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('forum.make_post') }}">
                    Create Post
                </a>
            </li>

            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('loginreg.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('loginreg.register') }}">
                    Register
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('forum.see_all_questions') }}">
                    See All Questions
                </a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{{ url_for('forum.see_all_questions') }}">
                    See All Questions
                </a>
            </li>

            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="container h-100 d-flex justify-content-center">
    <div class="jumbotron my-auto">
        <h4 class="display-3">Search for other posts</h4>
        <form action="/" class="form-inline my-2 my-lg-0" method="POST">
            {{ search_form.csrf_token }}
            {{ search_form.search_query(class="form-control", placeholder="Search") }}
            {% if search_form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in search_form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ search_form.submit(class="btn btn-outline-success") }}
        </form>
        <a href="{{ url_for('forum.see_all_questions') }}">Or, show all questions</a>
    </div>
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        Don't have an account yet? <a href="{{ url_for('loginreg.register') }}">Sign Up!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h2>Log In</h2>
                <form action="" method="post">
                    <div class="form-group">
                        {{ form.csrf_token }}
                        {{ form.email.label(class="form-control-label") }}
                        {{ form.email(class="form-control form-control-lg") }}
                        {% if form.email.errors %}
                        <div class="alert alert-warning" role="alert">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {{ form.password(class="form-control form-control-lg") }}
                        {% if form.password.errors %}
                        <div class="alert alert-warning" role="alert">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.submit(class="form-control form-control-lg") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

flask_app/templates/make_post.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form action="" method="post">
                    {{ form.csrf_token }}
                    <h2>Ask your question here:</h2>
                    <div class="form-group">
                        <div class="form-group">
                            {{ form.title.label(class="form-control-label")}}
                            {{ form.title(class="form-control form-control-lg") }}
                        {% if form.description.errors %}
                            <div class="alert alert-warning" role="alert">
                                    {% for error in form.description.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <div class="form-group">
                            {{ form.description.label(class="form-control-label")}}
                            {{ form.description(class="form-control form-control-lg") }}
                        {% if form.description.errors %}
                            <div class="alert alert-warning" role="alert">
                                    {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                            </div>
                        {% endif %}
                        </div>
                         <div class="form-group">
                            {{ form.submit(class="form-control form-control-lg") }}
                         </div>
                    </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% if dublicate_flag %}
    <div>
        <h6> We found another subject matching yours:</h6>
        <a href="{{ url_for('forum.see_question',question_id = id_reference) }}"> Take me there</a>
    </div>
{% endif %}
{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        Already have an account? <a href="{{ url_for('loginreg.login') }}">Log In!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h2>Sign up</h2>
                <form action="" method="post">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}
                        {{ form.username(class="form-control form-control-lg") }}
                        {% if form.username.errors %}
                        <div class="alert alert-warning" role="alert">
                            {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {{ form.email(class="form-control form-control-lg") }}
                        {% if form.email.errors %}
                        <div class="alert alert-warning" role="alert">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {{ form.password(class="form-control form-control-lg") }}
                        {% if form.password.errors %}
                        <div class="alert alert-warning" role="alert">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                        {% if form.confirm_password.errors %}
                        <div class="alert alert-warning" role="alert">
                            {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.about_me.label(class="form-control-label") }}
                        {{ form.about_me(class="form-control form-control-lg") }}
                        {% if form.about_me.errors %}
                        <div class="alert alert-warning" role="alert">
                            {% for error in form.about_me.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.submit(class="form-control form-control-lg") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

flask_app/templates/search_results.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        {% if error_msg %}
        <div class="alert alert-danger">
            {{ error_msg }}
        </div>
        {% else %}
        <h1> Search results for {{ query }}</h1>
        {% for question in search_results %}
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{{ url_for('forum.see_question', question_id=question.id) }}">{{
                                question.title }}</a></h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ question.commenter.username }}</h6>
                        <p class="card-text">{{ question.description }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}

flask_app/templates/see_all_questions.html
{% extends "header.html" %}
{% block content %}
<h3> Scroll through all of the questions here:</h3>
{% if questions %}
{% for question in questions %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ url_for('forum.see_question', question_id=question.id) }}">{{ question.title }}</a></h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ question.commenter.username }}</h6>
                <p class="card-text">{{ question.description }}</p>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<p>There are no questions yet.</p>
{% endif %}

{% endblock %}